name: analytics_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/new-nt-guna-beta-keystore.jpeg
    - assets/5547212-uhd_4096_2160_25fps.mp4
    - assets/Linkedin-Like-Icon-Thumbup500.png
    - assets/Screenshot 2024-07-26 at 7.02.39 PM.png
    - assets/Screenshot 2024-07-26 at 7.07.10 PM.png
    - assets/Screenshot 2024-07-26 at 7.03.21 PM.png
